### PR TITLE
Remove channels field from GET_ALL_LEADS_QUERY.

### PR DESCRIPTION
**Pull request by Arzoid29**

### CODE REVIEW

**Review by AudryLopez — COMMENTED** [review]
Why r u removing this?

**Review by AudryLopez — APPROVED** [review]

**Comment by kaioken** [comment]
@AudryLopez i dont see who is using it and consumes lots of date, can we add a flag instead of removing it ?

**Review by jerlyrosa — CHANGES_REQUESTED** [review]
delete the type in the lead interface also

**Comment by Arzoid29** [comment]
> delete the type in the lead interface also

its being used in other part so cant be removed

**Review by jerlyrosa — APPROVED** [review]

**Pull request merged**
